### ISSUE TITLE
Pending transaction loader

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#110]
During the wallet changes, we lost this pending indicator in the top right

<img width="591" alt="image" src="https://github.com/open-dollar/od-app/assets/35622595/d76cc109-f51a-4d8b-9592-30ddc545f836">

**Comment by jahabeebs** [comment]
@pi0neerpat The pending loader still works, it just looks a little different because we changed the loading spinner to be the keyp style spinner

Image of pending loader

<img width="189" alt="pendingloader" src="https://github.com/open-dollar/od-app/assets/47253537/e2c4155d-abef-4b9f-93ac-b41c2512ed8f">

Demo

https://github.com/open-dollar/od-app/assets/47253537/0e6b3da8-fec8-4c4c-b74b-ba1ff260e96f
