### ISSUE TITLE
Risk status as a factor of liquidation, safety ratios

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#154]
Related to https://github.com/open-dollar/svg-playground/issues/4

Currently the risk status for vaults is determined from hard-coded outcome, eg 120% is liquidation

However the liq ratio will be different for each collateral type

The status should be based off a factor of the liquidation ratio, rather than hardcoded

**Comment by jahabeebs** [comment]
> Related to [open-dollar/svg-playground#4](https://github.com/open-dollar/svg-playground/issues/4)
> 
> Currently the risk status for vaults is determined from hard-coded outcome, eg 120% is liquidation
> 
> However the liq ratio will be different for each collateral type
> 
> The status should be based off a factor of the liquidation ratio, rather than hardcoded

@pi0neerpat I've been looking into this with your suggestions from today and I think if every collateral will have a different liquidation ratio then we would need to assign a specific risk factor value for each collateral (or liquidation ratio). Otherwise I don't think there's a specific number that we could add or multiply to make all of them behave like the other. For example, here is our current function:

```
export const ratioChecker = (currentLiquidationRatio: number, minLiquidationRatio: number) => {
    // Assuming minLiquidationRatioPercent is 120% for now
    const minLiquidationRatioPercent = minLiquidationRatio * 100

    // lowRiskLowerBound set to 151%
    const lowRiskLowerBound = minLiquidationRatioPercent * 1.25833
    // elevatedRiskLowerBound set to 137%
    const elevatedRiskLowerBound = minLiquidationRatioPercent * 1.14167
    // highRiskLowerBound set to 120%
    const highRiskLowerBound = minLiquidationRatioPercent

    if (currentLiquidationRatio < highRiskLowerBound && currentLiquidationRatio > 0) {
        return 4
    } else if (currentLiquidationRatio >= lowRiskLowerBound) {
        return 1
    } else if (currentLiquidationRatio < lowRiskLowerBound && currentLiquidationRatio >= elevatedRiskLowerBound) {
        return 2
    } else if (currentLiquidationRatio < elevatedRiskLowerBound && currentLiquidationRatio >= highRiskLowerBound) {
        return 3
    } else {
        return 0
    }
}
```

If minLiquidationRatio will be different for each collateral, then "low", "elevated", "high", and "liquidation" will also be different for each collateral. We would have to control for this by either adding some kind of riskFactors parameter that will specify where low/elevated/high/liquidation is for a particular collateral/liquidation ratio. Like this:

```
/**
 * Check the risk state of the current liquidation ratio given a configurable minLiquidationRatio
 * and bounds for different risk levels
 * @param currentLiquidationRatio
 * @param minLiquidationRatio
 * @param riskFactors An object containing multipliers for different risk levels
 */
export const ratioChecker = (
    currentLiquidationRatio: number,
    minLiquidationRatio: number,
    riskFactors: {
        lowRiskFactor: number,
        elevatedRiskFactor: number,
        highRiskFactor: number
    }
) => {
    const minLiquidationRatioPercent = minLiquidationRatio * 100;

    const lowRiskLowerBound = minLiquidationRatioPercent * riskFactors.lowRiskFactor;
    const elevatedRiskLowerBound = minLiquidationRatioPercent * riskFactors.elevatedRiskFactor;
    const highRiskLowerBound = minLiquidationRatioPercent * riskFactors.highRiskFactor;

    if (currentLiquidationRatio < highRiskLowerBound && currentLiquidationRatio > 0) {
        return 4;
    } else if (currentLiquidationRatio >= lowRiskLowerBound) {
        return 1;
    } else if (
        currentLiquidationRatio < lowRiskLowerBound &&
        currentLiquidationRatio >= elevatedRiskLowerBound
    ) {
        return 2;
    } else if (
        currentLiquidationRatio < elevatedRiskLowerBound &&
        currentLiquidationRatio >= highRiskLowerBound
    ) {
        return 3;
    } else {
        return 0;
    }
};
``` 
and then we'd have to call the function like this:
```
const riskFactorsForCollateralA = {
    lowRiskFactor: 1.25833,
    elevatedRiskFactor: 1.14167,
    highRiskFactor: 1.0,
};

const state = ratioChecker(Number(newCollateralRatio), Number(collateralRatio), riskFactorsForCollateralA);
``` 

I don't understand otherwise how we could add or multiply a specific number that makes every minLiquidationRatio work for every collateral
