### ISSUE TITLE
Operations - common labels across organization

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#229]
We already have a global organization setting for labels, however this only takes effect one-time when creating a new repo. Instead we need a way to update labels across all our repos easily.

Research how we can easily accomplish this. Jacob mentioned maybe a config file we can place in the .github folder for each repo, rather than manually creating each label.

- Label names and colors must be consistent

**Comment by jahabeebs** [comment]
@pi0neerpat in the usekeyp org I can see the .github repo and the labels info (https://github.com/UseKeyp/.github) but I can't see either in opendollar. can you make .github public or add me there?

**Comment by jahabeebs** [comment]
@pi0neerpat I've added a .github folder with the necessary manage-your-labels action. It runs but doesn't take effect--I think because we need to provide an Actions secret called PAT to the organization with repo and write:org permissions

see code here:

```
    env:
      # Create a classic token with permissions: repo and write:org
      BOT_TOKEN: ${{ secrets.PAT }}
```
      
would you be able to generate the PAT and add it to settings? Unfortunately it only lets me generate PATs for the keyp org

<img width="1333" alt="Screenshot 2024-01-19 at 1 58 22 PM" src="https://github.com/open-dollar/od-app/assets/47253537/c46cb64f-ee51-4729-b39c-b4498e072ba6">

**Comment by pi0neerpat** [comment]
Thanks looks like it worked successfully
