### ISSUE TITLE
merge `optimism-hai`

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#324]
1. merge dev into optimism-hai and run locally on arbitrum testnet. Test that everything works ok for our OD testnet.
2. Merge optimism-hai into dev
3. Update vercel hai deployment to point to dev

**Comment by jahabeebs** [comment]
@pi0neerpat 

After locally merging with dev:

Arbitrum sepolia:
- Can't create vaults for any collateral
- Can't borrow OD on existing vaults
- Can withdraw but can't withdraw + repay or repay at all

Optimism
- Able to repay, haven't been able to test other functions because it requires at least 150 HAI which I don't have

**Comment by jahabeebs** [comment]
@pi0neerpat 

I've identified the reason why this is failing and I've made an issue to fix it

https://github.com/open-dollar/od-sdk/issues/64

**Comment by pi0neerpat** [comment]
Done
