### ISSUE TITLE
Auto-connect wallets

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#329]
May be related to #327

1. Wallet is not automatically connected when I arrive to a page.

Eg. Navigate to https://app.dev.opendollar.com/vaults/627

**Comment by jahabeebs** [comment]
@pi0neerpat I think the app is providing the expected behavior

when Metamask has connected to the app it automatically reconnected when you get to the site

https://github.com/open-dollar/od-app/assets/47253537/1e5deaf7-6187-46ff-8333-f3ec6ea53b10

when Metamask has disconnected to the site or never connected to the app it will need manual reconnection

https://github.com/open-dollar/od-app/assets/47253537/f84c4419-3b3e-41f5-bcdf-ffc3b66c698b

**Comment by pi0neerpat** [comment]
Closing as the issue is with Metamask requiring a manual connection every time, while other wallets like Rabby do not
