### ISSUE TITLE
Fuul SDK:  Sign prior to Vault Creation

### ISSUE THREAD

**Issue by Seroxdesign** [open-dollar/od-app#483]
To follow up on: 
https://github.com/open-dollar/od-app/pull/482

We want

```TS
    const sendConnectWalletEvent = async (walletAddress: string) => {
        const time = new Date().toDateString()
        const signature = await provider?.getSigner().signMessage(`Accept affiliate on ${time}`)
        const response = await Fuul.sendConnectWallet({
            address: walletAddress,
            signature,
            message: `Accept affiliate on ${time}`,
        })
        return response
    }
```

To trigger only when a user is ready to create a vault facilitator, if all goes well, allow them to sign the message, before signing the transaction:
![image](https://github.com/open-dollar/od-app/assets/69639595/a64d1237-b646-4ce2-baa8-03d563fb8b7d)

Additionally, improving the signature message would be helpful: Something like
`Sign to verify your address and access our points rewards program ${time}`

**Comment by jahabeebs** [comment]
@Seroxdesign I pushed my changes to your fuul-sdk branch because I had to move the init from the branch to App.tsx instead of leaving it in useFuulSDK.ts so that we can initialize Fuul before calling the method when creating the vault facilitator. Here's what it looks like now:

(see console where I logged to show what's going on)

https://github.com/open-dollar/od-app/assets/47253537/e6c293aa-99d6-49d2-bf5c-db798aa600da

**Comment by jahabeebs** [comment]
added to https://github.com/open-dollar/od-app/pull/482
