### ISSUE TITLE
View internal balances

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#557]
Depends on [#80](https://github.com/open-dollar/od-sdk/issues/80)

- Show internal balance in vault row
- Show internal balance on vault page
- Allow user to withdraw balance using `BasicActions.collectTokenCollateral`

**Comment by pi0neerpat** [comment]
![Image](https://github.com/open-dollar/od-app/assets/35622595/feb13cc1-5b97-47c8-b3f2-1a1e8d958ea3)

**Comment by jahabeebs** [comment]
@pi0neerpat this is the SDK code I added for us to call collectTokenCollateral:
```ts

    collectTokenCollateral(managerAddress: string, collateralJoinAddress: string, safeId: BigNumberish, deltaWad: BigNumberish) {
        return this.getProxiedTransactionRequest(
            this.proxyActionCore.populateTransaction.collectTokenCollateral(
                managerAddress,
                collateralJoinAddress,
                safeId,
                deltaWad
            )
        )
    }
```

What i'm not sure about is why we need deltaWad here--I assume this represents the amount of the balance the user is trying to withdraw. Shouldn't we just max this number out? I'm hoping that once a vault has an internal balance and we get that info from the SDK then that amount can be used as the deltaWad value and all the internal balance can be withdrawn rather than having the user specify an amount
