### ISSUE TITLE
Webflow meta tags

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#648]
See "Website Metadata" section here https://docs.google.com/document/d/1zjB_U417VUYlMcyn15eP-lYskPEKAQGneAPUk59XGq0/edit?usp=sharing

**Comment by jahabeebs** [comment]
@pi0neerpat I've finished updating the meta tags for Webflow and I've published them. There were some things I couldn't edit though:

1) Webflow does not support meta keywords: https://university.webflow.com/lesson/seo-title-meta-description?topics=seo
And Google has not supported them since 2009: https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag

2) Where is the about us page? I don't think this exists in the Webflow deployment

3) The How It Works section is the same page as the homepage, so we cannot add meta tags or we'd override the homepage meta tags

## Screenshots

Meta tags in production

<img width="254" alt="Screenshot 2024-07-22 at 4 31 56 PM" src="https://github.com/user-attachments/assets/c66951f3-176b-4b50-af3a-90a2f8dfd6de">

<img width="585" alt="Screenshot 2024-07-22 at 4 32 16 PM" src="https://github.com/user-attachments/assets/d511d4a6-234f-452a-a270-3abd1597e77c">

**Comment by pi0neerpat** [comment]
Done
